# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-21 08:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face', '0003_customermessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='DevelopmentStage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('picture', models.ImageField(upload_to='')),
            ],
        ),
    ]
