# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-26 10:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face', '0004_developmentstage'),
    ]

    operations = [
        migrations.AddField(
            model_name='developmentstage',
            name='name_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='developmentstage',
            name='name_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='developmentstage',
            name='text_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='developmentstage',
            name='text_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='name_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='name_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='name_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='name_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='role_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='role_ru',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
