# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-29 07:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face', '0006_auto_20160526_1103'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('name_en', models.CharField(max_length=255, null=True)),
                ('name_ru', models.CharField(max_length=255, null=True)),
                ('desctiption', models.TextField()),
                ('desctiption_en', models.TextField(null=True)),
                ('desctiption_ru', models.TextField(null=True)),
                ('snippet', models.TextField()),
                ('snippet_en', models.TextField(null=True)),
                ('snippet_ru', models.TextField(null=True)),
                ('html_tag_for_picture', models.TextField()),
            ],
        ),
    ]
