# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-29 09:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('face', '0007_service'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='desctiption',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='desctiption_en',
            new_name='description_en',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='desctiption_ru',
            new_name='description_ru',
        ),
    ]
