# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-29 10:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face', '0008_auto_20160529_0942'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='programming_frameworks',
            field=models.TextField(default='django'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='programming_frameworks_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='programming_frameworks_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='programming_languages',
            field=models.TextField(default='python'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='programming_languages_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='programming_languages_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='programming_tools',
            field=models.TextField(default='nginx'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='programming_tools_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='programming_tools_ru',
            field=models.TextField(null=True),
        ),
    ]
