# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-04 05:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face', '0009_service_technologies'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgrammingFramework',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='programming')),
            ],
        ),
        migrations.CreateModel(
            name='ProgrammingLanguage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='programming')),
            ],
        ),
        migrations.CreateModel(
            name='ProgrammingTool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='programming')),
            ],
        ),
        migrations.RemoveField(
            model_name='service',
            name='programming_frameworks',
        ),
        migrations.RemoveField(
            model_name='service',
            name='programming_frameworks_en',
        ),
        migrations.RemoveField(
            model_name='service',
            name='programming_frameworks_ru',
        ),
        migrations.RemoveField(
            model_name='service',
            name='programming_languages',
        ),
        migrations.RemoveField(
            model_name='service',
            name='programming_languages_en',
        ),
        migrations.RemoveField(
            model_name='service',
            name='programming_languages_ru',
        ),
        migrations.RemoveField(
            model_name='service',
            name='programming_tools',
        ),
        migrations.RemoveField(
            model_name='service',
            name='programming_tools_en',
        ),
        migrations.RemoveField(
            model_name='service',
            name='programming_tools_ru',
        ),
        migrations.AddField(
            model_name='programmingtool',
            name='service',
            field=models.ManyToManyField(to='face.Service'),
        ),
        migrations.AddField(
            model_name='programminglanguage',
            name='service',
            field=models.ManyToManyField(to='face.Service'),
        ),
        migrations.AddField(
            model_name='programmingframework',
            name='service',
            field=models.ManyToManyField(to='face.Service'),
        ),
    ]
