# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-04 06:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face', '0010_auto_20160604_0553'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programmingframework',
            name='service',
        ),
        migrations.RemoveField(
            model_name='programminglanguage',
            name='service',
        ),
        migrations.RemoveField(
            model_name='programmingtool',
            name='service',
        ),
        migrations.AddField(
            model_name='programmingframework',
            name='services',
            field=models.ManyToManyField(related_name='programming_frameworks', to='face.Service'),
        ),
        migrations.AddField(
            model_name='programminglanguage',
            name='services',
            field=models.ManyToManyField(related_name='programming_languages', to='face.Service'),
        ),
        migrations.AddField(
            model_name='programmingtool',
            name='services',
            field=models.ManyToManyField(related_name='programming_tools', to='face.Service'),
        ),
    ]
